language: php
services: mysql
php:
  - "5.5"
before_install:
  - mysql -u root -e "CREATE DATABASE IF NOT EXISTS archie;"
before_script:
  - chmod +x test/syntax-check
  - mysql -u root archie < test/test_db.sql
  - cp config/units.csv.dist config/units.csv
  - cp config/quads.csv.dist config/quads.csv
  - cp test/test_settings.php config/settings.php
 
script:
  - test/syntax-check
  - php test/run_tests.php
